### PR TITLE
List guru, add, edit and delete

### PR DESCRIPTION
**Pull request by ismailfajar81**
all of the function has been implemented and successfully executed. so please give me some review of all codes I've modified . Thanks for all help

### CODE REVIEW

**Comment by hendisantika** [comment]
Aya Conflict tuch. Benerkeun heula. Nyobaan benerkeun.

**Review by hendisantika — COMMENTED** [review]
OK

**Comment by ismailfajar81** [comment]
> Aya Conflict tuch. Benerkeun heula. Nyobaan benerkeun.
atos nya

**Review by hendisantika — APPROVED** [review]
OK

**Pull request merged**
